#+TITLE: Clip Keeper
#+AUTHOR: MaskedRedstonerProZ
#+EMAIL: maskedredstonerproz@gmail.com
#+DESCRIPTION: Very simple rofi frontend for pass

:toc:
- [[#about-clip-keeper][About Clip Keeper]]
- [[#license][License]]
- [[#download/installation][Download/Installation]]


* About Clip Keeper

Clip Keeper is a very simple graphical frontend, for the Simple Password Store (pass), that utilizes the Rofi launcher to display the actual passwords, and allow the user to copy them using the same mechanisms one would normally use in rofi, to launch a particular program (mouse click, return key press on selection). After copying, they stay in the clipboard for 45 seconds, after which they are cleared, and must be copied again, for further use.

* License

Clip Keeper is licensed by the GNU General Public License version 3.0 or later, which states that any willing party is allowed to ammend, extend or otherwise contribute to the development of Clip Keeper. Permission is also granted to redistribute Clip Keeper as is, however one may like to do so, which extends to any derivative works that one may develop, with the condition of course, that the redistribution or the derivative work, contains a copy of the GNU General Public License version 3.0 or later, and makes it available to the end user.

* Download/Installation

Clip Keeper is available for download/installation at the following official locations, any others that may be found, while permitted to exist, are to be used according to the user's own discretion, as they lack official developer support, and safety guarantee.

** Direct download from Gitlab

Users may download a copy of Clip Keeper from the official [[https://gitlab.com/MaskedRedstonerProZ/clip-keeper][gitlab repository]] in the following ways:

*** The download/install script

A simple script which downloads and installs the rofi mode, as well as a shell script required for starting Clip Keeper as intented + other functionality, one may copy the script, or run the command below, according to their preference.

#+BEGIN_SRC shell
curl https://gitlab.com/MaskedRedstonerProZ/clip-keeper/install | sh
#+END_SRC

#+BEGIN_SRC shell :tangle install :tangle-mode (identity #o755)
#!/usr/bin/env sh

# Copyright (C) 2025 MaskedRedstonerProZ
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# SPDX-License-Identifier: GPL-3.0-or-later

set -uo pipefail

LATEST_VERSION="release-1.1.0"
DOWNLOAD_URL="https://gitlab.com/MaskedRedstonerProZ/clip-keeper/-/releases/${LATEST_VERSION}/downloads/clip-keeper.tar.gz"
CLIP_KEEPER_MODI_LOCATION="/opt/clip-keeper/modi"
CLIP_KEEPER_CONFIG_LOCATION="/opt/clip-keeper/config/config.rasi"

: "${PREFIX:=${pkgdir:-/}}"

cat >> "${CLIP_KEEPER_CONFIG_LOCATION}" << EOF
@import "~/.config/rofi/config.rasi"

configuration {
    modes: "clip-keeper";
    kb-element-next: "";
    kb-move-char-forward: "Control+f,Alt+Right";
    kb-custom-1: "Tab,Right";
}

inputbar {
    children: [prompt,entry,case-indicator];
}
EOF

main() {

	if [[ $EUID -ne 0 ]]; then
		if command -v sudo >/dev/null; then
			exec sudo bash "$0" "$@"
		else
			echo "This installer requires root privileges. Please run with sudo."
			exit 1
		fi
	fi

	wget -qO- "${DOWNLOAD_URL}" | tar -JxC "${PWD}"

	mv "${PWD}/libclip_keeper.so" "${PREFIX}/${CLIP_KEEPER_MODI_LOCATION}"
	mv "${PWD}/clip-keeper" "${PREFIX}/usr/bin/clip-keeper"

	trap "rm -rf {${PWD}/libclip_keeper.so,${PWD}/clip-keeper}"
}

main "${@}"
#+END_SRC


*** A direct ArchLinux package download

An ArchLinux package, which installs to ~/usr/bin~.

** Download/Install from my custom ArchLinux repository maskedredstonerproz-core

Users may add my custom ArchLinux repository, as described below, in which I've made Clip Keeper available, among other custom builds of existing software.

In ~/etc/pacman.conf~ add the following:

#+BEGIN_SRC
[maskedredstonerproz-core]
Server = https://gitlab.com/MaskedRedstonerProZ/$repo/-/raw/main/$arch
#+END_SRC
